name: sample
on: 
  workflow_dispatch:
    inputs:
      int_value:
        description: "choose a number between 1 and 2"
        required: true
        type: choice
        options:
          - "1"
          - "2"
jobs:
  print_output_value:
    runs-on: ubuntu-latest
    steps:
      - name: print the output
        run: |
          res=${{inputs.int_value}}
          if [ "$res" -eq "1" ]; then
            echo "chosen number is one"
          else
            echo "chosen number is 2"
          fi
          
          
  
        
        
              
  
